import { Toaster } from "sonner";
import "./globals.css";



export const metadata = {
  title: "Deal drop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}
        <Toaster richColors/>
      </body>

    </html>
  );
}
